Project/urls.py
# my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView  # new
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import HomeView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls')),  # new
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('blog/', include('blogs.urls')),
                  path('forums/', include('forums.urls')),
                  path('', HomeView.as_view(), name='home'),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('', include('products.urls')),
                  path('cart', include('cart.urls')),
                  path('orders/', include('orders.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

forums/urls.py
# my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView  # new
from forums import views

urlpatterns = [
    path('', views.ForumList.as_view(), name='forums'),
    path('<slug:slug>/details/', views.ForumDetails.as_view(), name='forum-details'),
    path('topic/<slug:slug>/details/', views.TopicDetails.as_view(), name='forum-posts'),
    path('post/<slug:slug>/details/', views.PostDetails.as_view(), name='topic-post-details'),
    path('post/<slug:slug>/answer/', views.TopicAnswerCreate.as_view(), name='topic-post-answer'),
    path('post/<slug:slug>/answer/<int:id>/comment/', views.TopicAnswerCommentCreate.as_view(),
         name='topic-post-answer-comment'),
    path('post/<slug:slug>/answer/<int:answer_id>/upvote/', views.up_vote, name='topic-post-answer-upvote'),
    path('post/<slug:slug>/answer/<int:answer_id>/downvote/', views.down_vote, name='topic-post-answer-downvote'),

]

forums/models.py
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from django.urls import reverse

from django.conf import settings


class BaseModel(models.Model):
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Tag(BaseModel):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class ForumCategory(BaseModel):
    title = models.CharField(max_length=500)
    slug = AutoSlugField(populate_from='title')

    def __str__(self):
        return self.title


class Topic(BaseModel):
    title = models.CharField(max_length=500)
    category = models.ForeignKey(ForumCategory, on_delete=models.CASCADE)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = AutoSlugField(populate_from='title')

    @property
    def get_last_post(self):
        return self.topicposts_set.all().order_by('-id').first()

    def __str__(self):
        return self.title


class TopicPosts(BaseModel):
    title = models.CharField(max_length=500)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    content = models.TextField()
    slug = AutoSlugField(populate_from='title', default='test-slug')

    def __str__(self):
        return self.title


class TopicAnswer(BaseModel):
    topic_post = models.ForeignKey(TopicPosts, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()

    def can_vote(self, user_id):
        topic_vote = TopicVote.objects.filter(topic_answer=self, user_id=user_id).first()
        if topic_vote:
            return topic_vote.vote
        return None

    def total_votes(self):
        return self.topicvote_set.all().aggregate(total=Sum("vote"))["total"] or 0

    def up_vote_url(self):
        return reverse('topic-post-answer-upvote', args=[self.topic_post.slug, self.id])

    def down_vote_url(self):
        return reverse('topic-post-answer-downvote', args=[self.topic_post.slug, self.id])

    def __str__(self):
        return str(self.id)


class TopicVote(BaseModel):
    topic_answer = models.ForeignKey(TopicAnswer, on_delete=models.CASCADE)
    vote = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)


class TopicAnswerComment(BaseModel):
    topic_answer = models.ForeignKey(TopicAnswer, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()

    def __str__(self):
        return str(self.id)

forums/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, TemplateView

from blogs.models import Post, BlogComment
from forums.models import ForumCategory, Topic, TopicPosts, TopicAnswer, TopicAnswerComment, TopicVote


class ForumList(ListView):
    model = ForumCategory
    queryset = ForumCategory.objects.filter(is_active=True)
    context_object_name = 'forum_categories'
    template_name = 'forums.html'


class ForumDetails(DetailView):
    model = ForumCategory
    template_name = 'all_topics.html'

    def get_context_data(self, **kwargs):
        context = {}
        context['topics'] = Topic.objects.filter(category__slug=self.kwargs.get('slug'))
        return super().get_context_data(**context)


class TopicDetails(DetailView):
    model = Topic
    template_name = 'all_posts.html'

    def get_context_data(self, **kwargs):
        context = {}
        context['posts'] = TopicPosts.objects.filter(topic__slug=self.kwargs.get('slug'))
        return super().get_context_data(**context)


class PostDetails(DetailView):
    model = TopicPosts
    template_name = 'forum_post_details.html'
    context_object_name = 'post'


class TopicAnswerCreate(LoginRequiredMixin, CreateView):
    model = TopicAnswer
    fields = ['content']

    def get_success_url(self):
        return reverse('topic-post-details', kwargs={'slug': self.kwargs.get('slug')})

    def form_valid(self, form):
        post = TopicPosts.objects.filter(slug=self.kwargs.get('slug')).first()
        form.instance.topic_post_id = post.id
        form.instance.user = self.request.user
        return super().form_valid(form)


class TopicAnswerCommentCreate(LoginRequiredMixin, CreateView):
    model = TopicAnswerComment
    fields = ['content']

    def get_success_url(self):
        return reverse('topic-post-details', kwargs={'slug': self.kwargs.get('slug')})

    def form_valid(self, form):
        post = TopicAnswer.objects.filter(id=self.kwargs.get('id')).first()
        form.instance.topic_answer_id = post.id
        form.instance.user = self.request.user
        return super().form_valid(form)


# class UpVoteView(LoginRequiredMixin, TemplateView):
#     model = TopicAnswerComment
#     fields = ['content']
#
#     def get_success_url(self):
#         return reverse('topic-post-details', kwargs={'slug': self.kwargs.get('slug')})
#
#     def form_valid(self, form):
#         post = TopicAnswer.objects.filter(id=self.kwargs.get('id')).first()
#         form.instance.topic_answer_id = post.id
#         form.instance.user = self.request.user
#         return super().form_valid(form)

@login_required
def up_vote(request, slug, answer_id):
    topic_answer = TopicAnswer.objects.filter(id=answer_id).first()
    topic_vote, _ = TopicVote.objects.get_or_create(topic_answer=topic_answer, vote=1, user=request.user)
    topic_vote.vote = 1
    topic_vote.save()
    return redirect(reverse('topic-post-details', kwargs={'slug': slug}))


@login_required
def down_vote(request, slug, answer_id):
    topic_answer = TopicAnswer.objects.filter(id=answer_id).first()
    topic_vote, _ = TopicVote.objects.get_or_create(topic_answer=topic_answer, vote=1, user=request.user)
    topic_vote.vote = -1
    topic_vote.save()
    return redirect(reverse('topic-post-details', kwargs={'slug': slug}))

forums/templates/all_posts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="forums">
            <h5>Forums</h5>
            {#            {% for category in forum_categories %}#}
            <div class="table-responsive singleForum">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Answers</th>
                        <th>Posted by</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for post in posts %}
                        <tr>
                            <td>
                                <div class="communityF"><span class="chatIcon"></span>
                                    <p><a href="{% url 'topic-post-details' slug=post.slug %}">{{ post.title }}</a></p></div>
                            </td>
                            <td>{{ post.topicanswer_set.all.count }}</td>
                            <td>

                                <div class="lastpost"><span class="imgWrap"><img
                                        src="{% static 'images/dp1.jpg' %}"
                                        width="56" height="56"
                                        alt="dp"></span>
                                    <p>{{ post.user.first_name }}
                                        <span>{{ post.created_at|date }} | {{ post.created_at|time }}</span>
                                    </p></div>


                            </td>

                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
            {#            {% endfor %}#}
        </div>
    </div>
{% endblock %}

forums/templates/all_topics.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="forums">
            <h5>Forums</h5>
            {#            {% for category in forum_categories %}#}
            <div class="table-responsive singleForum">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Community</th>
                        <th>Posts</th>
                        <th>Last Post</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for topic in topics %}
                        <tr>
                            <td>
                                <div class="communityF"><span class="chatIcon"></span>
                                    <p>{{ topic.title }}</p></div>
                            </td>
                            <td>{{ topic.topicposts_set.all.count }}</td>
                            <td>
                                {% if topic.get_last_post %}
                                    <div class="lastpost"><span class="imgWrap"><img
                                            src="{% static 'images/dp1.jpg' %}"
                                            width="56" height="56"
                                            alt="dp"></span>
                                        <p>{{ topic.get_last_post.user.first_name }}
                                            <span>{{ topic.get_last_post.created_at|date }} | {{ topic.get_last_post.created_at|time }}</span>
                                        </p></div>
                                {% endif %}

                            </td>
                            <td><a href="{% url 'forum-posts' slug=topic.slug %}" class="btn btn-primary">All Posts</a>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
            {#            {% endfor %}#}
        </div>
    </div>
{% endblock %}

forums/templates/forum_post_details.html
{% extends 'base.html' %}
{% load static %}
{% load form_extras %}

{% block content %}
    <div class="container">
        <div class="communityPage">
            <h5>Community</h5>
            <div class="que">
                <div class="commWrap ">
                    <div class="community">
                        <div class="imgWrap">
                            <img src="{% static 'images/dp.jpg' %}" height="" width="" alt="dp">
                        </div>
                        <div class="commCont">
                            <h6>{{ post.title }}</h6>
                            <p class="time">Asked by <span class="name">{{ post.user.first_name }}</span>
                                on {{ post.created_at|date }} <span
                                        class="post"> {{ post.user.topicposts_set.all.count }} posts</span></p>
                            <p>{{ post.content }}</p>
                            <div class="keywords">
                                {% for tag in post.tags.all %}
                                    <span>{{ tag.title }}</span>
                                {% endfor %}
                            </div>
                        </div>
                        <button type="button" class="reply btn btn-secondary" data-toggle="modal"
                                data-target="#comment-modal">
                            <i class="fa fa-edit"></i>Reply
                        </button>


                    </div>
                </div>
            </div>
            <span class="answer">{{ post.topicanswer_set.all.count }} Answers</span>


            {% for answer in post.topicanswer_set.all %}


                <div class="modal" id="comment-modal-answer-{{ answer.id }}">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <!-- Modal body -->
                            <div class="modal-body">
                                <form action="{% url 'topic-post-answer-comment' slug=post.slug id=answer.id %}"
                                      method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="comment">Comment:</label>
                                        <textarea class="form-control" rows="5" id="content" name="content"></textarea>
                                    </div>
                                    <button type="submit" class="btn btn-secondary">Submit</button>
                                </form>
                            </div>


                        </div>
                    </div>
                </div>


                <div class="commWrap ans">
                    <div class="community">
                        <div class="left">
                            <div class="imgWrap">
                                <img src="{% static 'images/dp.jpg' %}" height="" width="" alt="dp">
                            </div>
                            {#                            <button class="link share"><i class="fa fa-share-square"></i>Share</button>#}
                            {#                            <button class="link improve"><i class="fa fa-wrench"></i>Improve</button>#}
                        </div>
                        <div class="commCont">
                            <h6>{{ post.title }}</h6>
                            <p class="time">Answered by <span class="name">{{ answer.user.first_name }}</span>
                                on {{ answer.created_at|date }} <span
                                        class="post"> {{ answer.user.topicposts_set.all.count }} posts</span></p>
                            <p>{{ answer.content }}</p>
                        </div>
                        <div class="right">
                            <button type="button" class="reply btn btn-secondary" data-toggle="modal"
                                    data-target="#comment-modal-answer-{{ answer.id }}">
                                <i class="fa fa-edit"></i>Reply
                            </button>
                            <div class="slideContArrows">
                                {% get_something answer user.id as can_vote %}

                                {% if can_vote == 1 %}
                                    <button style="color: green;" href="{{ answer.up_vote_url }}"
                                            class="btn fa fa-caret-up"></button>
                                {% elif can_vote != 1 or can_vote == None %}
                                    <a href="{{ answer.up_vote_url }}" class="btn fa fa-caret-up"></a>
                                {% endif %}
                                <p>{{ answer.total_votes }}</p>
                                {% if can_vote == -1 %}
                                    <button class="btn fa fa-caret-down" style="color: red;"></button>
                                {% elif can_vote != -1 or can_vote == None %}
                                    <a href="{{ answer.down_vote_url }}" class="btn fa fa-caret-down"></a>
                                {% endif %}

                            </div>
                        </div>
                    </div>

                    {% for answer_comment in answer.topicanswercomment_set.all %}
                        <div class="community">
                            <div class="imgWrap">
                                <img src="{% static 'images/dp.jpg' %}" height="" width="" alt="dp">
                            </div>
                            <div class="commCont">
                                <p class="time">Answerd by <span
                                        class="name">{{ answer_comment.user.first_name }}</span>
                                    on {{ answer_comment.created_at|date }}</p>
                                <p>{{ answer_comment.content }} </p>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            {% endfor %}

        </div>
    </div>


    <!-- Button to Open the Modal -->

    <!-- The Modal -->
    <div class="modal" id="comment-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal body -->
                <div class="modal-body">
                    <form action="{% url 'topic-post-answer' slug=post.slug %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="comment">Comment:</label>
                            <textarea class="form-control" rows="5" id="content" name="content"></textarea>
                        </div>
                        <button type="submit" class="btn btn-secondary">Submit</button>
                    </form>
                </div>


            </div>
        </div>
    </div>


{% endblock %}

forums/templates/forums.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="forums">
            <h5>Forums</h5>
            {% for category in forum_categories %}
                <div class="table-responsive singleForum">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Community</th>
                            <th>Topics</th>
                            <th>Posts</th>
                            <th>Last Post &nbsp;&nbsp;<a href="{% url 'forum-details' slug=category.slug %}" class="btn btn-primary">All Topics</a></th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for topic in category.topic_set.all|slice:"0:3" %}
                            <tr>
                                <td>
                                    <div class="communityF"><span class="chatIcon"></span>
                                        <p><a href="{% url 'forum-posts' slug=topic.slug %}" class="btn btn-default">{{ topic.title }}</a></p></div>
                                </td>
                                <td>{{ category.topic_set.all.count }}</td>
                                <td>{{ topic.topicposts_set.all.count }}</td>
                                <td>
                                    {% if topic.get_last_post %}
                                        <div class="lastpost"><span class="imgWrap"><img
                                                src="{% static 'images/dp1.jpg' %}"
                                                width="56" height="56"
                                                alt="dp"></span>
                                            <p>{{ topic.get_last_post.user.first_name }}
                                                <span>{{ topic.get_last_post.created_at|date }} | {{ topic.get_last_post.created_at|time }}</span>
                                            </p></div>
                                    {% endif %}

                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}