Project/urls.py
# my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView  # new
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import HomeView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls')),  # new
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('blog/', include('blogs.urls')),
                  path('forums/', include('forums.urls')),
                  path('', HomeView.as_view(), name='home'),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('', include('products.urls')),
                  path('cart', include('cart.urls')),
                  path('orders/', include('orders.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from accounts import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

cart/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

products/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('products/search/', views.search_product, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('<int:id>/<slug:slug>/like/', views.product_like, name='product_like'),
    path('<int:id>/<slug:slug>/rate/', views.product_rate, name='product_rate'),
]

accounts/models.py
from datetime import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import pre_save
from django.db.transaction import atomic
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    profile_picture = models.ImageField(upload_to='profile-pictures/', blank=True)
    email = models.EmailField(unique=True, max_length=75)
    phone = PhoneNumberField(blank=True, default=None, null=True)
    address = models.CharField(null=True, default=None, max_length=150, blank=True)
    username = models.CharField(null=True, max_length=150, default=None, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    subscription = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return 'Id:{0} Name :{1} {2}, email: {3}'.format(self.id, self.first_name, self.last_name, self.email)


@receiver(pre_save, sender=User)
@atomic
def pre_save_user(sender, instance, *args, **kwargs):
    if not getattr(instance, 'pk'):
        new_user = '{}{}'.format(datetime.now().strftime("%Y%m%d%S"), User.objects.all().count())
        instance.registration_no = 'Parusa-' + str(new_user)

accounts/forms.py
# from django import forms
from django.contrib.auth.forms import UserCreationForm
# from django.forms import ModelForm
from django.conf import settings

from accounts.models import User


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    # password = forms.CharField(min_length=8, widget=forms.TextInput(attrs={'class': 'form-control'}))

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

from accounts.forms import UserForm
from blogs.models import Post
from products.models import Product, Category
from cart.forms import CartAddProductForm


class SignUp(generic.CreateView):
    form_class = UserForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


class HomeView(generic.TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        kwargs['blogs'] = Post.objects.filter(is_active=True).order_by('-id')[:3]
        kwargs['products'] = Product.objects.filter(product_type=Product.PRODUCT)[:10]
        kwargs['range'] = range(5)
        kwargs['cart_product_form'] = CartAddProductForm()
        return kwargs

templates/account.html
{% extends 'base.html' %}
{% load static %}
{% block content %}{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Calling System</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/allstyles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body class="home">
<header class="header">
    <div class="container">
        <div class="top-bar">
            <div class="headNav">
                <ul>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'logout' %}">Logout</a></li>

                    {% else %}
                        <li><a href="{% url 'signup' %}">Sign Up</a></li>
                        <li><a href="{% url 'login' %}">Login</a></li>
                    {% endif %}


                    <li><a href="{% url 'posts' %}">Blog</a></li>
                    <li><a href="{% url 'forums' %}">Forum</a></li>
{#                    {% if user.is_authenticated %}#}
{#                        <li><a href="#">My Account</a></li>#}
{#                    {% endif %}#}

                </ul>

                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}

                        {#                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">#}
                        {#                            {{ totail_items }} item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}#}
                        {#                        </a>#}

                        <div class="cart">
                            <a href="{% url "cart:cart_detail" %}" class="flaticon-shopping-cart"></a>
                            <div class="notify">{{ totail_items }}</div>
                        </div>
                    {% else %}
                        <div class="cart">
                            <a href="#" class="flaticon-shopping-cart"></a>
                            <div class="notify">0</div>
                        </div>
                    {% endif %}
                {% endwith %}


            </div>
            <div class="headTop">
                <a href="{% url 'home' %}" class="logo"><img src="{% static 'images/logo.jpg' %}" height="130"
                                                             width="234" alt="logo"></a>
                <div class="headTopDrop">
                    <select class="form-control categories" id="sel1" class="form-control">
                        <option hidden="">All Categories</option>
                        {% for cat in categories %}
                            <option value="{{ cat.get_absolute_url }}"
                                    {% if category and cat.id == category.id %}selected{% endif %}>{{ cat.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <!-- <div class="headTopSearch"> -->
                <form action="{% url 'products:product_list' %}" method="get">
                    <div class="searchWrap">
                        <!--  <div class="search"> -->

                        <input type="text" name="search" placeholder="Search products by SKU or name"
                               class="form-control" {% if search %}value="{{ search }}" {% endif %}>
                        <!-- </div> -->
                        <button type="submit" class="btn btn-primary">Search</button>

                    </div>
                </form>
                <!-- </div> -->
            </div>
        </div>
    </div>
</header>
<main>

<!-- templates/home.html -->
    {% block content %}
    {% endblock %}
</main>
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <h6>Store Logo</h6>
                <p>In hac habitasse platea dictumst. Vivamus adipiscing fermentum quam volutpat aliquam. Integer et elit
                    eget elit facilisis tristique. Nam vel iaculis mauris.</p>
                <div class="socialIcons">
                    <a href="#" class="flaticon-facebook-logo-button"></a>
                    <a href="#" class="flaticon-twitter-logo-button"></a>
                    <a href="#" class="flaticon-youtube-logotype"></a>
                </div>
            </div>
            <div class="col-md-2 fooNav ">
                <h6 class="fooTitle">Site Map </h6>
                <ul class="fooUl">
                    <li><a href="#">About us</a></li>
                    <li><a href="#">Our Team</a></li>
                    <li><a href="#">Products</a></li>
                    <li><a href="#">Jobs</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-md-2 ">
                <h6 class="fooTitle">Other Links</h6>
                <ul class="fooUl">
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Terms and Conditions</a></li>
                    <li><a href="#">Downloads</a></li>
                    <li><a href="#">Research</a></li>
                    <li><a href="#">FAQ</a></li>
                </ul>
            </div>
            <div class="col-md-3 ">
                <div class="news">
                    <h6 class="fooTitle newsTitle">Sign Up To Our Newsletter</h6>
                    <input type="text" name="" style="background: #e2e2e2; border-color:#e2e2e2;"
                           placeholder="Enter email address" class="form-control">
                    <button class="btn btn-secondary subBtn">Subscribe</button>
                </div>
            </div>
        </div>
    </div>
</footer>
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugins.js' %}"></script>
<script type="text/javascript" src="{% static 'js/system.js' %}"></script>

<script>


    $('select.categories').click(function () {
        var open = $(this).data("isopen");
        if (open) {
            window.location.href = $(this).val()
        }
        //set isopen to opposite so next time when use clicked select box
        //it wont trigger this event
        $(this).data("isopen", !open);
    });
</script>
</body>

</html>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block title %}Home{% endblock %}

{% block content %}

    <div class="headSlider">
        <div class="slide">
            <img src="{% static 'images/slider.jpg' %}" width="1910" height="484" alt="slider">
            <div class="slideContent">
                <h2>Raspberry Pi3 Model B+</h2>
                <p>1.4GHz 64-bit quad-core processor, dual-band wireless LAN, Bluetooth 4.2/BLE, faster Ethernet, and
                    Power-over-Ethernet support (with separate PoE HAT)</p>
                <button type="submit" class="btn btn-primary">Buy Now</button>
            </div>
        </div>
        <div class="slide">
            <img src="{% static 'images/slider.jpg' %}" width="1910" height="484" alt="slider">
            <div class="slideContent">
                <h2>Raspberry Pi3 Model B+</h2>
                <p>1.4GHz 64-bit quad-core processor, dual-band wireless LAN, Bluetooth 4.2/BLE, faster Ethernet, and
                    Power-over-Ethernet support (with separate PoE HAT)</p>
                <button type="submit" class="btn btn-primary">Buy Now</button>
            </div>
        </div>
        <div class="slide">
            <img src="{% static 'images/slider.jpg' %}" width="1910" height="484" alt="slider">
            <div class="slideContent">
                <h2>Raspberry Pi3 Model B+</h2>
                <p>1.4GHz 64-bit quad-core processor, dual-band wireless LAN, Bluetooth 4.2/BLE, faster Ethernet, and
                    Power-over-Ethernet support (with separate PoE HAT)</p>
                <button type="submit" class="btn btn-primary">Buy Now</button>
            </div>
        </div>
    </div>
    <section class="bestProducts">
        <h5 class="title">Best Selling Products</h5>
        <div class="container">
            <div class="proSlider">

                {% for product in products %}
                    <div class="slide ">
                        <a href="{{ product.get_absolute_url }}" class="products">
                            <img src="{{ product.image.url }}" width="262" height="173" alt="product">
                            <div class="slideCont">
                                <h6>{{ product.name }}</h6>
                                <p>{{ product.description|truncatechars:80 }}</p>
                                <p class="price">${{ product.price }}</p>
                                <div class="rating">
                                    {% for i in range %}
                                        {% if forloop.counter <= product.average_ratings %}
                                            <i class="star flaticon-star-1"></i>
                                        {% else %}
                                            <i class="star flaticon-star"></i>
                                        {% endif %}
                                    {% endfor %}
                                    <p class="starCount">({{ product.rating_set.all.count }})</p>
                                </div>
                            </div>
                            {% if product.available %}
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    <div hidden>
                                        {{ cart_product_form|crispy }}
                                    </div>
                                    <button type="submit" class="btn btn-primary">Add to cart</button>
                                </form>

                            {% else %}
                                <button type="button" class="btn btn-primary">Out of Stock</button>
                            {% endif %}

                            <span class="search"></span>
                        </a>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>
    <section class="latestBlogs">
        <h5 class="title">Latest Blogs and Forums</h5>
        <div class="container">
            <div class="row">
                {% for blog in blogs %}
                    {% if forloop.counter == 1 %}
                        <div class="col-md-6">
                            <div class="blog blogLeft">
                                <img src="{{ blog.main_image.url }}" height="482" width="868" alt="blog">
                                <h6><a href="{% url 'blog-post-details' slug=blog.slug %}" style="color: white;"> {{ blog.title }}</a></h6>
                            </div>
                        </div>


                    {% else %}
                        <div class="col-md-6">
                            <div class="blog blogRight">
                                <img src="{{ blog.main_image.url }}" height="150" width="868" alt="blog">
                                <h6><a href="{% url 'blog-post-details' slug=blog.slug %}" style="color: white;">{{ blog.title }}</a></h6>
                            </div>

                            <div class="blog blogRight">
                                <img src="{{ blog.main_image.url }}" height="150" width="868" alt="blog">
                                <h6><a href="{% url 'blog-post-details' slug=blog.slug %}" style="color: white;">{{ blog.title }}</a></h6>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}


            </div>
        </div>
    </section>

{% endblock %}

templates/signup.html
<!-- templates/registration/login.html -->
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Signup{% endblock %}


{% block content %}

    <div class="container">
        <div class="signUp">
            <h5>Signup</h5>

            <form class="signUpForm" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="signupBtn btn btn-info">Signup</button>
            </form>

        </div>
    </div>
{% endblock %}