Project/urls.py
# my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView  # new
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import HomeView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls')),  # new
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('blog/', include('blogs.urls')),
                  path('forums/', include('forums.urls')),
                  path('', HomeView.as_view(), name='home'),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('', include('products.urls')),
                  path('cart', include('cart.urls')),
                  path('orders/', include('orders.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

products/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('products/search/', views.search_product, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('<int:id>/<slug:slug>/like/', views.product_like, name='product_like'),
    path('<int:id>/<slug:slug>/rate/', views.product_rate, name='product_rate'),
]

products/models.py
import math
from autoslug import AutoSlugField
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from django.urls import reverse
from django.conf import settings

# from orders.models import Order, OrderItem


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = AutoSlugField(populate_from='name', unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:product_list_by_category', args=[self.slug])


class Product(models.Model):
    ACCESSORY = 'accessory'
    PRODUCT = 'product'
    PRODUCT_TYPES = ((ACCESSORY, 'Accessory'), (PRODUCT, 'Product'))

    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = AutoSlugField(populate_from='name', unique=True, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    total_views = models.IntegerField(default=0)
    parent = models.ForeignKey('Product', null=True, blank=True, on_delete=models.CASCADE)
    product_type = models.CharField(max_length=100, choices=PRODUCT_TYPES, default=PRODUCT)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def total_likes(self):
        return ProductLike.objects.filter(product=self).count()

    def get_absolute_url(self):
        return reverse('products:product_detail', args=[self.id, self.slug])

    def get_like_url(self):
        return reverse('products:product_like', args=[self.id, self.slug])

    def get_rate_url(self):
        return reverse('products:product_rate', args=[self.id, self.slug])

    def total_items_sold(self):
        return self.order_items.all().aggregate(total=Sum("quantity"))["total"] or 0

    def average_ratings(self):
        if self.rating_set.all().count() > 0:
            return math.ceil(
                self.rating_set.all().aggregate(total=Sum('rate'))['total'] / self.rating_set.all().count())
        return 0


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    def __str__(self):
        return str(self.id)


class ProductLike(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like = models.BooleanField(default=True)

    def __str__(self):
        return str(self.id)


class CustomContent(models.Model):
    title = models.CharField(max_length=50, default='')
    content = RichTextUploadingField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)


class Rating(models.Model):
    COMMENT = 'comment'
    RATE = 'RATE'
    RATE_TYPE = (
        (COMMENT, 'Comment'),
        (RATE, 'Rate')
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    message = models.TextField()
    rate_type = models.CharField(choices=RATE_TYPE, default=RATE, max_length=20)
    rate = models.IntegerField(default=1)

    def __str__(self):
        return str(self.id)

products/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from cart.forms import CartAddProductForm
from products.models import Category, Product, ProductLike, Rating


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'range': range(5)
    }
    return render(request, 'product/list.html', context)


def search_product(request, category_slug=None):
    search_term = request.GET.get('search', '')

    products = Product.objects.filter(name__icontains=search_term, available=True)

    context = {
        'search': search_term,
        'products': products
    }
    return render(request, 'product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    product.total_views += 1
    product.save()
    related_items = Product.objects.filter(parent=product)
    context = {
        'product': product, 'related_items': related_items, 'cart_product_form': CartAddProductForm(), 'range': range(5)
    }
    return render(request, 'product/detail.html', context)


@login_required
def product_like(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    user = request.user
    ProductLike.objects.get_or_create(product=product, user=user)
    product.save()
    return redirect(product.get_absolute_url())


@login_required
def product_rate(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)

    comment = request.POST.get('comment', '')
    rating = request.POST.get('rating', 0)
    if product:
        if not Rating.objects.filter(user=request.user, product=product, rate_type=Rating.RATE).exists():
            Rating.objects.create(user=request.user, product=product, message=comment, rate=rating)
        else:
            Rating.objects.create(user=request.user, product=product, message=comment, rate=rating,
                                  rate_type=Rating.COMMENT)

        return redirect(product.get_absolute_url())
        # ProductLike.objects.get_or_create(product=product, user=user)
        # product.save()
        # return redirect(product.get_absolute_url())

        #
        # class ProductRateView(LoginRequiredMixin, TemplateView):
        #     template_name = 'products/product_details.html'
        #
        #     def post(self, request, *args, **kwargs):
        #         slug = kwargs.get('slug', None)
        #         comment = request.POST.get('comment', '')
        #         rating = request.POST.get('rating', 0)
        #         product = Product.objects.filter(slug=slug).first()
        #         if product:
        #             if not Rating.objects.filter(user=self.request.user, product=product, rate_type=Rating.RATE).exists():
        #                 Rating.objects.create(user=self.request.user, product=product, message=comment, rate=rating)
        #             else:
        #                 Rating.objects.create(user=self.request.user, product=product, message=comment, rate=rating,
        #                                       rate_type=Rating.COMMENT)
        #
        #         return redirect(reverse('product_detail', args=[slug]))

products/templates/product/detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/rating.css' %}">
    <div class="container">
        <div class="productDetailPage">
            <div class="productTop">
                <div class="row">


                    <div class="col-lg-7 col-md-6">
                        <div class="proDetailSliderWrap">
                            <div class="proDetailSlider">

                                {% for image in product.productimage_set.all %}
                                    <div class="slide">
                                        <div class="imgWrap">
                                            <img src="{{ image.image.url }}" alt="" height=""
                                                 width="">
                                        </div>
                                    </div>
                                {% endfor %}

                            </div>
                            <div class="proDetailSliderNav">
                                {% for image in product.productimage_set.all %}
                                    <div class="slide">
                                        <div class="imgWrap">
                                            <img src="{{ image.image.url }}" alt="" height=""
                                                 width="">
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-6">
                        <div class="proInfo">
                            <div class="row">

                            </div>
                            <div class="rating">
                                {% for i in range %}
                                    {% if forloop.counter <= product.average_ratings %}
                                        <i class="star flaticon-star-1"></i>
                                    {% else %}
                                        <i class="star flaticon-star"></i>
                                    {% endif %}
                                {% endfor %}

                                <p class="starCount">({{ product.rating_set.all.count }})</p>
                            </div>
                            <h6>{{ product.name }}</h6>
                            <p>{{ product.description }}</p>
                            <p class="price">${{ product.price }}</p>
                            <p class="stock">
                                {% if product.available %}
                                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                                        {% csrf_token %}
                                        {{ cart_product_form|crispy }}
                                        <button type="submit" class="btn btn-primary">Add to cart</button>
                                    </form>

                                {% else %}Out of Stock{% endif %}
                            </p>

                            <div class="proSocialIcons">
                                <a href="#" class="flaticon-facebook-letter-logo"></a>
                                <a href="#" class=" flaticon-twitter-logo-silhouette"></a>
                                <a href="#" class="flaticon-envelope"></a>
                                <a href="#" class="flaticon-share"></a>
                                <span>Share</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="proRatingInfo">
                <p><span>{% if user.is_authenticated %}<a href="{{ product.get_like_url }}">Like</a>{% else %}
                    Likes{% endif %}</span> ({{ product.total_likes }})</p>
                <p><span>Products Sold</span>({{ product.total_items_sold }})</p>
                <p><span>Views</span>({{ product.total_views }})</p>
            </div>
            <div class="proTabs">
                <ul class="nav nav-tabs">
                    {% for content in product.customcontent_set.all %}
                        <li><a {% if forloop.counter0 == 0 %}class="active show"{% endif %} data-toggle="tab"
                               href="#tab-{{ content.id }}">{{ content.title }}</a></li>
                    {% endfor %}
                </ul>
                <div class="tab-content" style="margin-left: 20px;">

                    {% for content in product.customcontent_set.all %}
                        <div id="tab-{{ content.id }}"
                             class="tab-pane fade {% if forloop.counter0 == 0 %}active show{% endif %}">
                            {{ content.content|safe }}
                        </div>
                    {% endfor %}

                </div>
            </div>
            <div class="proRelated">
                <h6 class="title">Related Products</h6>
                <div class="proSlider">
                    {% for prod in related_items %}
                        <div class="slide ">
                            <a href="{{ prod.get_absolute_url }}" class="products">
                                <img src="{{ prod.image.url }}" width="262" height="173" alt="product">
                                <div class="slideCont">
                                    <div class="slideInnerCont">
                                        <div class="slideContText">
                                            <h6>{{ prod.name }}</h6>
                                            <p>{{ prod.description|truncatechars:80 }} </p>
                                        </div>
                                        {#                                        <div class="slideContArrows">#}
                                        {#                                            <button class="btn fa fa-caret-up"></button>#}
                                        {#                                            <p>50</p>#}
                                        {#                                            <button class="btn fa fa-caret-down"></button>#}
                                        {#                                        </div>#}
                                    </div>
                                    <p class="price">${{ prod.price }}</p>
                                    <div class="rating">
                                        {% for i in range %}
                                            {% if forloop.counter <= prod.average_ratings %}
                                                <i class="star flaticon-star-1"></i>
                                            {% else %}
                                                <i class="star flaticon-star"></i>
                                            {% endif %}
                                        {% endfor %}

                                        <p class="starCount">({{ prod.rating_set.all.count }})</p>
                                    </div>
                                </div>

                                {% if prod.available %}
                                    <form action="{% url "cart:cart_add" prod.id %}" method="post">
                                        {% csrf_token %}
                                        <div hidden>
                                            {{ cart_product_form|crispy }}
                                        </div>
                                        <button type="submit" class="btn btn-primary">Add to cart</button>
                                    </form>
                                {% else %}
                                    <button type="button" class="btn btn-primary">Out of Stock</button>
                                {% endif %}
                                <span class="search"></span>
                            </a>
                        </div>
                    {% endfor %}


                </div>
            </div>

            <div class="input_comment">

                <form method="post" action="{{ product.get_rate_url }}">
                    {% csrf_token %}
                    <textarea name="comment" placeholder="Please Rate Us" required class="form-control"></textarea>

                    <br>
                    <br>


                    <div>
                        {% if not user_product_rate %}
                            <fieldset class="rating-new">
                                <input type="radio" id="star5" name="rating"
                                       value="5"/><label
                                    class="full"
                                    for="star5"
                                    title="Awesome - 5 stars"></label>
                                <input type="radio" id="star4half" name="rating"
                                       value="5"/><label class="half"
                                                         for="star4half"
                                                         title="Pretty good - 4.5 stars"></label>
                                <input type="radio" id="star4" name="rating"
                                       value="4"/><label
                                    class="full"
                                    for="star4"
                                    title="Pretty good - 4 stars"></label>
                                <input type="radio" id="star3half" name="rating"
                                       value="4"><label class="half"
                                                        for="star3half"
                                                        title="Meh - 3.5 stars"></label>
                                <input type="radio" id="star3" name="rating"
                                       value="3"/><label
                                    class="full"
                                    for="star3"
                                    title="Meh - 3 stars"></label>
                                <input type="radio" id="star2half" name="rating"
                                       value="3"/><label class="half"
                                                         for="star2half"
                                                         title="Kinda bad - 2.5 stars"></label>
                                <input type="radio" id="star2" name="rating"
                                       value="2"/><label
                                    class="full"
                                    for="star2"
                                    title="Kinda bad - 2 stars"></label>
                                <input type="radio" id="star1half" name="rating"
                                       value="2"/><label class="half"
                                                         for="star1half"
                                                         title="Meh - 1.5 stars"></label>
                                <input type="radio" id="star1" name="rating"
                                       value="1"/><label
                                    class="full"
                                    for="star1"
                                    title="Sucks big time - 1 star"></label>
                                <input type="radio" id="starhalf" name="rating"
                                       value="1"/><label
                                    class="half" for="starhalf"
                                    title="Sucks big time - 0.5 stars"></label>
                            </fieldset>
                        {% endif %}
                        <div class="text-right">
                            <button type="submit" class="btn btn-danger">Post</button>
                        </div>
                    </div>


                </form>
            </div>


            <div class="proReviews">
                <h6 class="title">Reviews</h6>
                {% for rate in product.rating_set.all %}
                    <div class="singleReview">
                        <div class="imgWrap">
                            <img src="{% static 'images/dp1.jpg' %}" width="" height="" alt="">
                        </div>
                        <div class="review">
                            <p class="name">Julia</p>
                            <p>{{ rate.message }}</p>
                            <div class="rating">
                                {% for i in range %}
                                    {% if forloop.counter <= rate.rate %}
                                        <i class="star flaticon-star-1"></i>
                                    {% else %}
                                        <i class="star flaticon-star"></i>
                                    {% endif %}

                                {% endfor %}

                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>


{% endblock %}

products/templates/product/list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
    <main class="main">
        <div class="container">
            <div class="productspage">
                <div class="row">
                    <div class="col-lg-3 col-md-4">
                        <div class="proLeft">
                            <a href="#" class="todaySearch">
                                <h6>Today's Offer</h6>
                                <img src="images/product-w.jpg" alt="product" width="" height="">
                                <h5>Raspberry Pi3 Model B+ </h5>
                                <p class="offer">30% OFF</p>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-9 col-md-8">
                        <div class="proRight">
                            <div class="proTitle">
                            {% if search %}
                                <h6>Search: {{ search }}</h6>
                            {% endif %}
                                {% if category %}
                                    <h6> Category: {{ category.name }}</h6>
                                {% endif %}

                                {#                                <div class="pagination">#}
                                {#                                    <p>Showing 60 of 392</p>#}
                                {#                                    <a href="#" class="arrow flaticon-arrow-angle-pointing-to-left"></a>#}
                                {#                                    <a href="#" class="arrow  flaticon-right-arrow-angle"></a>#}
                                {#                                </div>#}
                            </div>
                            {#                            <p class="sortP"><span>Sort:</span> By Popularity</p>#}
                            <hr>
                            <div class="productsList">
                                <div class="row">
                                    {% for product in products %}
                                        <div class="col-lg-4 col-sm-6">
                                            <a href="#" class="products">
                                                <img src="{{ product.image.url }}" width="262" height="173"
                                                     alt="product">
                                                <div class="slideCont">
                                                    <h6>{{ product.name }}</h6>
                                                    <p>{{ product.description|truncatechars:80 }}</p>
                                                    <p class="price">${{ product.price }}</p>
                                                    <div class="rating">
                                                        {% for i in range %}
                                                            {% if forloop.counter <= product.average_ratings %}
                                                                <i class="star flaticon-star-1"></i>
                                                            {% else %}
                                                                <i class="star flaticon-star"></i>
                                                            {% endif %}
                                                        {% endfor %}
                                                        <p class="starCount">({{ product.rating_set.all.count }})</p>
                                                    </div>
                                                </div>

                                                {% if product.available %}
                                                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                                                        {% csrf_token %}
                                                        <div hidden>
                                                            {{ cart_product_form|crispy }}
                                                        </div>
                                                        <button type="submit" class="btn btn-primary">Add to cart
                                                        </button>
                                                    </form>

                                                {% else %}
                                                    <button type="button" class="btn btn-primary">Out of Stock</button>
                                                {% endif %}

                                                <span class="search"></span>
                                            </a>
                                        </div>
                                    {% endfor %}

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>


{% endblock %}